# Generated by Django 4.1 on 2022-10-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productattribute_productsize_product_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
