# Generated by Django 4.1 on 2022-11-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_made_in_product_pre_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_percentage',
            new_name='discount_percentage',
        ),
    ]
