# Generated by Django 4.1 on 2023-03-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_product_productvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ManyToManyField(related_name='images', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='product',
            field=models.ManyToManyField(related_name='videos', to='products.product'),
        ),
    ]
